const CART_KEY='essense_cart',FAV_KEY='essense_favorites';let products=[];let cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]');let favorites=JSON.parse(localStorage.getItem(FAV_KEY)||'[]');
const save=()=>{localStorage.setItem(CART_KEY,JSON.stringify(cart));localStorage.setItem(FAV_KEY,JSON.stringify(favorites));updateCounts()};
const updateCounts=()=>{let c=document.getElementById('cartCount'),f=document.getElementById('favCount');if(c)c.textContent=cart.reduce((s,x)=>s+x.qty,0);if(f)f.textContent=favorites.length};
const toast=m=>{let t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
function toggleFav(id,e){if(e)e.stopPropagation();id=Number(id);favorites.includes(id)?favorites=favorites.filter(x=>x!==id):favorites.push(id);save();renderProducts();renderFavorites();if(document.querySelector('.product-page'))renderProduct()}
function addToCart(id){let p=products.find(x=>x.id==id);if(!p)return;let item=cart.find(x=>x.id==id);item?item.qty++:cart.push({...p,qty:1});save();toast('Додано до кошика 🛒')}
function card(p){let active=favorites.includes(p.id);return `<article class="card" onclick="location.href='product.html?id=${p.id}'"><button class="heart ${active?'active':''}" onclick="toggleFav(${p.id},event)">${active?'♥':'♡'}</button><div class="card-img"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="card-body"><div class="brand">${p.brand}</div><h3>${p.name}</h3><div class="volume">100 ml</div><div class="price">${p.price} грн <span class="old">${p.oldPrice} грн</span></div></div></article>`}
function renderProducts(){let el=document.getElementById('products');if(el)el.innerHTML=products.map(card).join('')}
function renderFavorites(){let el=document.getElementById('favorites');if(el){let ps=products.filter(p=>favorites.includes(p.id));el.innerHTML=ps.length?ps.map(card).join(''):'<div style="grid-column:1/-1;padding:50px 0;color:#888">Поки що тут порожньо. Додай улюблені аромати ♡</div>'}}
function renderProduct(){let el=document.getElementById('productPage');if(!el)return;let id=Number(new URLSearchParams(location.search).get('id')),p=products.find(x=>x.id===id);if(!p){el.innerHTML='<h2>Аромат не знайдено</h2>';return}let active=favorites.includes(p.id);el.innerHTML=`<div class="product-photo"><button class="heart ${active?'active':''}" onclick="toggleFav(${p.id},event)">${active?'♥':'♡'}</button><img src="${p.image}" alt="${p.name}"></div><div class="product-info"><div class="brand">${p.brand}</div><h1>${p.name}</h1><div class="volume">100 ml</div><div class="price">${p.price} грн <span class="old">${p.oldPrice} грн</span></div><p class="desc">${p.description}</p><div class="notes">${p.notes.map(n=>`<span class="note">${n}</span>`).join('')}</div><button class="gold-btn buy" onclick="addToCart(${p.id})">Замовити</button></div>`}
function renderCart(){let el=document.getElementById('cart');if(!el)return;if(!cart.length){el.innerHTML='<p style="color:#888;margin-top:35px">Кошик порожній.</p>';return}let total=cart.reduce((s,x)=>s+x.price*x.qty,0);el.innerHTML=cart.map(x=>`<div class="cart-row"><div style="display:flex;align-items:center;gap:15px"><img src="${x.image}"><div><b>${x.name}</b><div class="volume">100 ml × ${x.qty}</div></div></div><strong>${x.price*x.qty} грн</strong></div>`).join('')+`<div class="cart-total">Разом: ${total} грн</div><button class="gold-btn buy" style="margin-top:25px" onclick="toast('Напиши нам для оформлення замовлення')">Оформити замовлення</button>`}
fetch('products.json').then(r=>r.json()).then(d=>{products=d.filter(p=>!p.name.toLowerCase().includes('absolutely'));renderProducts();renderFavorites();renderProduct();renderCart();updateCounts();document.body.classList.add('loaded')}).catch(()=>document.body.classList.add('loaded'));
window.addEventListener('load',()=>setTimeout(()=>document.body.classList.add('loaded'),1800));updateCounts();
